# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171107_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='img_url',
            new_name='image',
        ),
    ]
